import { json, type RequestEvent } from '@sveltejs/kit';
import { type Hex, keccak256, encodePacked } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
// import * as snarkjs from 'snarkjs';
import { createRequire } from 'module';
import fs from 'fs';
import path from 'path';

// SERVER WALLET (Oracle)
// GUID: Use a secure environment variable for this in production!
// For development, we can use a generated one or the user's dev wallet.
const PRIVATE_KEY = process.env.ORACLE_PRIVATE_KEY || '0x1e2f25281ecd844abb64843d9833efbe36a1ad72af92625641f44ed666444217';
const account = privateKeyToAccount(PRIVATE_KEY as Hex);

export async function POST({ request }: RequestEvent) {
    // Lazy load snarkjs to avoid build-time issues with web-worker
    const require = createRequire(import.meta.url);
    const snarkjs = require('snarkjs');
    try {
        const body = await request.json();
        const { proof, publicSignals, address } = body;

        if (!proof || !publicSignals || !address) {
            return json({ error: 'Missing required parameters' }, { status: 400 });
        }

        // 1. Load Verification Key
        // Ensure this file exists! (Generated by compile_circuit.ps1)
        const vKeyPath = path.resolve('src/lib/zk/verification_key.json');

        if (!fs.existsSync(vKeyPath)) {
            console.error('Verification key not found at:', vKeyPath);
            return json({ error: 'Server misconfiguration: Verification Key missing' }, { status: 500 });
        }

        const vKey = JSON.parse(fs.readFileSync(vKeyPath, 'utf8'));

        // 2. Verify ZK Proof
        // publicSignals[0] = score (Assuming Score is the first public output/input in circuit definition)
        const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);

        if (!isValid) {
            return json({ error: 'Invalid Zero-Knowledge Proof' }, { status: 403 });
        }

        // 3. Extract Score
        // Note: Check game.circom public signals order. Usually outputs come first.
        // Signal input seed, input claimedScore, output score.
        // Wait, if claimedScore is public input, and score is output...
        // snarkjs order: [output_score, input_seed, input_claimedScore]
        const verifiedScore = BigInt(publicSignals[0]);
        console.log(`Verified Score for ${address}: ${verifiedScore}`);

        // 4. Sign the Score (Oracle)
        // Message: keccak256(packed(address, score))
        // This binds the score to the specific user address.
        const messageHash = keccak256(
            encodePacked(
                ['address', 'uint256'],
                [address as Hex, verifiedScore]
            )
        );

        const signature = await account.signMessage({
            message: { raw: messageHash }
        });

        return json({
            success: true,
            score: verifiedScore.toString(),
            signature
        });

    } catch (error: any) {
        console.error('ZK Verification Error:', error);
        return json({ error: 'Internal Server Error', details: error.message }, { status: 500 });
    }
}
